### ISSUE TITLE
bug - cold SDK loses Rust String type in compound assignment

### ISSUE THREAD

**Issue by dannymeijer** [dannys-code-corner/incan#896]
## Area

- Compiler (frontend/backend/codegen)

## Summary

Expected: a Rust function returning `String`, used as the right-hand side of `str += ...`, should retain its Incan string type in a cold compiled-SDK build. Codegen should lower the compound assignment through the string concatenation path, or reject the source clearly if the Rust return type cannot be established.

Actual: when a release compiler artifact builds an SDK provider in a fresh smoke job, the direct Rust call loses the string-aware lowering and generated Rust uses `String + String`. Rust rejects the generated provider with E0308. The same source can pass through a warmed in-process integration path, making the generated Rust environment-dependent.

This was exposed by #893 / PR #895 after adding internal UTF-8 byte-slice helpers. It is distinct from #852, which covered expected-context inference for generic Rust returns, and #846, which covers borrowing owned strings for Rust generic parameters.

## Reproduction steps

1. Build the release compiler once from the pre-hardening head of PR #895 (`ef0d110cb84b0634862a7d93e92660c26c988510`):

   ```bash
   make smoke-test-release
   ```

2. Copy only `target/release/incan` into a fresh checkout/job at the same commit, so the generated SDK provider and Rust inspection state are cold.

3. Compile an SDK consumer whose `stdlib-data` source contains the accepted direct compound-assignment shape:

   ```incan
   from rust::incan_stdlib::strings import str_slice_byte_range

   def append_range(text: str, start: int, end: int) -> str:
       mut out = ""
       out += str_slice_byte_range(text, start, end)
       return out
   ```

4. Run either smoke consumer that selects `stdlib-data`:

   ```bash
   make smoke-test-web-example
   make smoke-test-benchmarks-incan
   ```

Both failed in PR #895 CI jobs [88138373785](https://github.com/encero-systems/incan/actions/runs/29666688821/job/88138373785) and [88138373787](https://github.com/encero-systems/incan/actions/runs/29666688821/job/88138373787).

An explicit typed local avoids the invalid lowering:

```incan
part: str = str_slice_byte_range(text, start, end)
out += part
```

## Output / logs

```text
error[E0308]: mismatched types
  --> .../components/stdlib-data/src/regex/_core.rs:602:49
   |
   | out = out + str_slice_byte_range(&text, last_end, start);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`

error[E0308]: mismatched types
  --> .../components/stdlib-data/src/regex/_core.rs:617:29
   |
   | out = out + str_slice_from_byte_offset(&text, last_end);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
```

The two reconstruction forms produced six E0308 errors across three replacement loops. Materializing the Rust return as an explicitly typed `str` made cold web and benchmark provider builds compile successfully.

## Environment

- OS: Ubuntu 24.04 GitHub-hosted runner
- Rust: stable 1.97.1
- Incan: v0.5 development, PR #895 head `ef0d110cb84b0634862a7d93e92660c26c988510`
- Commands: `make smoke-test-web-example`, `make smoke-test-benchmarks-incan`
- CI run: https://github.com/encero-systems/incan/actions/runs/29666688821

**Comment by dannymeijer** [comment]
Reopened: the original cold SDK String compound-assignment defect still reproduces under Rust stable 1.97.1. Current main bc438e825 (CI run https://github.com/encero-systems/incan/actions/runs/29779732677) and PR #932 e72fc0b (CI run https://github.com/encero-systems/incan/actions/runs/29783321360) both emit the same generated stdlib-data regex E0308 String + String errors at lines 603, 618, 667, 683, 793, and 813, breaking web-example/examples/benchmarks smoke. This is not caused by #931. Follow-up acceptance: clean cold stdlib-data reproduction; correct binary/compound String lowering without type-name heuristics; cover affected Rust String metadata representations and generated regex output; prove web/example/benchmark smoke on stable and Rust 1.93 before #932 rebases.
